.PHONY: all

all:
	rpmbuild \
		--define "_defined_release `git rev-parse --short HEAD`" \
		--define "_defined_build_number `git rev-list HEAD --count`" \
		--define "pgmajor $(MAJOR)" \
		--define "pgmajorversion $(shell echo ${MAJOR} | sed 's/\.//g')" \
		-bb pg_stat_query_plans.spec 
